#include<stdio.h>
int main()
{
	int a,b;
	printf("\nEnter your department according to the following criteria:\nEnter 1 for CS\nEnter 2 for EE");
	scanf("%d",&a);
	switch(a)
	{
		case 1:
				{
					printf("\nEnter your year:\nEnter 1 for 1st year\nEnter 2 for 2nd year:  ");
					scanf("%d",&b);
					switch(b)
					{
					case 1: printf("\nIT FUNDAMENTALS AND APPLICATIONS\nPROGRAMMING FUNDAMENTALS\nFUNCTIONAL ENGLISH\nISLAMIC STUDIES\nAPPLIED PHYSICS\nIDEOLOGY AND CONSTITUTION OF PAKISTAN\nLOGIC DESIGN AND SWITCHING THEORY\nDESCRETE STRUCTURES\nOBJECT ORIENTED PROGRAMMING\nCALCULUS AND ANALYTICAL GEOMETRY\nPAKISTAN STUDIES"); break;
					case 2: printf("\nDATA STRUCTURES ALGORITHMS AND APPLICATIONS\nLINEAR ALGEBRA AND ORDINARY DIFFERENCIAL EQUATIONS\nPROBABILITY AND STATISTICS\nACADEMIC READING AND WRITING\nPROFESSIONAL ETHICS\nCIVICS AND COMMUNITY ENGAGEMENT\nCOMPUTER ARCHITECTURE AND ORGANIZATION\nDATABASE MANAGEMENT SYSTEM\nSOFTWARE ENGINEERING\nFINANCIAL AND COST ACCOUNTING\nMULTIVARIABLE CALCULUS\nCOMMUNITY SERVICE"); break;
					default: printf("\nInvalid input");
					}
				}break;
		case 2:
			{
				printf("\nEnter your year:\nEnter 1 for 1st year\nEnter 2 for 2nd year");
				scanf("%d",&b);
				switch(b)
				{
				case 1: printf("\nBASIC ELECTRICAL ENGINNERING\nFUNCTIONAL ENGLISH\nCALCULUS AND ANALYTICAL GEOMETRY\nIT FUNDAMENTALS AND APPLICATIONS\nISLAMIC STUDIES\nPAKISTAN STUDIES\nCIRCUIT ANALYSIS\n LINEAR ALGEBRA AND ORDINARY DIFFERENTIAL EQUATIONS\nCOMPUTER PROGRAMMING\nIDEOLOGY AND CONSTITUTION OF PAKISTAN\nAPPLIED PHYSICS"); break;
				case 2: printf("\nELECTRONIC DEVICES AND CIRCUITS\nDATA STRUCTURE AND ALGORITHMS\nMULTI VARIABLE CALCULUS\n ACADEMIC READING AND WRTING\nENGINEERING DRAWING\nCIVICSN AND COMMUNITY ENGAGEMENT"); break;
				default: printf("\nInvalid input");
				}
			} break;
			default:
				printf("\nIvalid input");
				
					
				
			
		
	}
	
}

